# Generated by Django 3.2 on 2021-04-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Mobile',
        ),
    ]
